# Generated by Django 2.1.4 on 2018-12-17 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20181217_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Student ID'),
            preserve_default=False,
        ),
    ]
