# Generated by Django 2.1.4 on 2018-12-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20181217_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='slug',
            new_name='student_id',
        ),
    ]
